### ISSUE TITLE
pytest_plugin doesn't work with pytest-xdist

### ISSUE THREAD

**Issue by curzona** [JetBrains/teamcity-python#11]
When I run <code>py.test -n 8 teamcity</code> to parallelize my test; testSuiteStarted, testStarted, and testSuiteFinished messages are missing.

Without xdist:
```
##teamcity[testSuiteStarted timestamp='2013-09-15T16:46:48.153' name='test_hello.py']

##teamcity[testStarted timestamp='2013-09-15T16:46:48.168' name='test_eval[3+5-8|]']
.
##teamcity[testFinished timestamp='2013-09-15T16:46:48.169' duration='0' name='test_eval[3+5-8|]']
```

With xdist:
```
scheduling tests via LoadScheduling
.
##teamcity[testFinished timestamp='2013-09-15T16:47:01.311' duration='1' name='test_eval[2+4-6|]']
.
##teamcity[testFinished timestamp='2013-09-15T16:47:01.311' duration='0' name='test_eval[3+5-8|]']
F
```

**Comment by shalupov** [comment]
Ok, I see two problems (notes for myself):

* Tests should be reported with special "flowId" which helps TeamCity to separate output from different threads. See http://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity (which is easy, just generate flowId for each thread)
* It badly interacts with testSuiteStarted/Finished. Is is required to call them per thread or smth else?

**Comment by shalupov** [comment]
Notes:
* py.test reports test status to main thread
* it's sufficient to report every test with flowId=test_id to make TeamCity happy

**Comment by shalupov** [comment]
Everyone, please check 1.10 release
