### ISSUE TITLE
Does not work with multiproccess and nosetests

### ISSUE THREAD

**Issue by altryne** [JetBrains/teamcity-python#19]
Hi,
So I'm using this plugin and loving it. Tried to upgrade our testing to multiproccess (runs locally without a problem)
And the build fails with 
```
AttributeError: 'NoSharedFixtureContextSuite' object has no attribute 'test'
```

When I manually go to the the server and run nosetests with this command, it works
```
nosetests --processes=1 --process-timeout=520 tests
```

But the same build step fails inside teamcity

**Comment by shalupov** [comment]
Should be fixed in teamcity-messages==1.11
