### ISSUE TITLE
Change format of teamcity messages for pytest

### ISSUE THREAD

**Issue by sashakruglov** [JetBrains/teamcity-python#44]
Hi there!

We started using `teamcity-messages` recently and had noticed that names of tests are formatted differently from XML report generated by `pytest`. This mismatch could lead to 2 issues:
* muted tests are reported as new failures
* test history could be lost

Example. If we had test `test_check_foo` in `test_bar.py` module, then
XML report would show name of the test as `test_bar.test_check_foo`, but `teamcity-messages` would format name of the test to `test_bar_py.test_check_foo`.

Is it possible to fix this issue?

**Comment by shalupov** [comment]
Hi! I can fix this issue (remove _py suffix, it's ugly), but I don't want to check all other cases of different names, so please report if you find them.

**Comment by sashakruglov** [comment]
Great, thanks!
Will wait for new package release to apply.

**Comment by shalupov** [comment]
I've released v1.13 to pypi

**Comment by sashakruglov** [comment]
Updated couple of days ago.
So far it works as expected.

Thank you again!
