### ISSUE TITLE
Race condition under parallel test execution

### ISSUE THREAD

**Issue by lewisc** [JetBrains/teamcity-python#51]
It seems this code is not resilient against race conditions caused by parallel test execution, is it possible to get that fixed?

**Comment by shalupov** [comment]
Yes, current code is for multi-process execution, not multithreading. Do you want to fix it?

**Comment by lewisc** [comment]
I will see what I can do

**Comment by lewisc** [comment]
https://github.com/JetBrains/teamcity-python/pull/52

**Comment by lewisc** [comment]
This seems fixed
