### ISSUE TITLE
Make teamcity-messages 2.0; support Python >= 2.7

### ISSUE THREAD

**Issue by msabramo** [JetBrains/teamcity-python#60]
or maybe Python >= 2.6, but please nothing older than that.

[Python 2.5.6](https://www.python.org/download/releases/2.5.6/) was released in May of 2011.

> under the current release policy, no security issues in Python 2.5 will be fixed anymore.

Bumping to teamcity-messages 2.0 would allow dropping these old versions of Python. This would make development and testing easier and would make for cleaner code. Also then `teamcity-messages` could support newer Python features like context managers. Imagine something like:

```python
with TeamcityServiceMessages.block('<blockName>'):
    do_stuff()
    do_more_stuff()
    oh_one_more_thing()
```

Folks using Python 2.4 or 2.5 could use the old versions of teamcity-messages.

Cc: @djeebus, @sudarkoff

**Comment by sudarkoff** [comment]
Great idea! :+1:

**Comment by shalupov** [comment]
We're investigating how to replace PyCharm (Python IDE from JetBrains) reporting code with this one.
Support of 2.4, 2.5, jython 2.5 is still required, so making two versions of it will be inconvenient at this time.

As for Python 2.6 CentOS 6 and Debian Squeeze (oldstable) are still widely used.
